### ISSUE TITLE
Errors Running Maven Build

### ISSUE THREAD

**Issue by bogolese** [codelibs/elasticsearch-analysis-extension#6]
I'm trying to build this project using "mvn clean install" (I know almost nothing about Maven -- this is simply the way I built a pom.xml ES plugin for a much older version of ES).

I am using JDK 11 (JDK 8 and JDK 17 fail outright) and the latest output is attached.  Any help/insight into the "proper" way to build is greatly appreciated!

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------< org.codelibs:elasticsearch-analysis-extension >------------
[INFO] Building elasticsearch-analysis-extension 8.5.3.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ elasticsearch-analysis-extension ---
[INFO] Deleting /pub/dev/elasticsearch-analysis-extension-8.5.x/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ elasticsearch-analysis-extension ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ elasticsearch-analysis-extension ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /pub/dev/elasticsearch-analysis-extension-8.5.x/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ elasticsearch-analysis-extension ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 18 source files to /pub/dev/elasticsearch-analysis-extension-8.5.x/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.997 s
[INFO] Finished at: 2023-02-07T15:40:01-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project elasticsearch-analysis-extension: Fatal error compiling: error: release version 17 not supported -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Regards,

Rich Bergmann

**Comment by marevol** [comment]
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project elasticsearch-analysis-extension: Fatal error compiling: error: release version 17 not supported -> [Help 1]

This plugin supports only Java 17.
I think you use a different Java version.

**Comment by bogolese** [comment]
Thank you for this marevol.  I have three JDKs installed, 8, 11, and 17.  The results I sent you were from 11 because I got further with that than any other.  This is what I did to "use" Java 17:


user@redacted:/pub/dev/elasticsearch-analysis-extension-8.5.x$ export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/
user@redacted:/pub/dev/elasticsearch-analysis-extension-8.5.x$ echo $JAVA_HOME
/usr/lib/jvm/java-17-openjdk-amd64/
user@redacted:/pub/dev/elasticsearch-analysis-extension-8.5.x$ mvn clean install
[ERROR] Error executing Maven.
[ERROR] java.lang.IllegalStateException: Unable to load cache item
[ERROR] Caused by: Unable to load cache item
[ERROR] Caused by: Could not initialize class com.google.inject.internal.cglib.core.$MethodWrapper


Is there another way to "coax" Maven to use Java 17 that I am not aware of?

Thanks again!  :)

Regards,

Rich Bergmann

**Comment by bogolese** [comment]
Okay, I'm sorry marevol.  I did a bit more spelunking and it appears that Maven 3.6.3, which is the version installed on my Ubuntu 20 OS, is not compatible with Java 17.  :(

I will update this when I figure out how to resolved this issue (probably a manual install of a newer version of Maven).  Please stand by . . .

Regards,

Rich Bergmann

**Comment by bogolese** [comment]
Okay, I had to manually upgrade to Maven 3.9.0 since there is not package manager upgrade for Ubuntu 20.  I essentially used the instructions that valerij dobler provided here:

It now builds.  I am now happy.  You may now close this case.

https://stackoverflow.com/questions/44438848/maven-crashes-when-trying-to-compile-a-project-error-executing-maven

Thank you!

Regards,

Rich Bergmann
